# Generated by Django 5.2 on 2025-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField()),
                ('name', models.CharField()),
                ('total', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('challenge', models.IntegerField()),
                ('extra', models.IntegerField()),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
    ]
