# Generated by Django 5.2 on 2025-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('orundum', models.IntegerField()),
                ('originium', models.IntegerField()),
                ('tikets', models.IntegerField()),
            ],
        ),
    ]
