# Generated by Django 5.2 on 2025-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tikets',
        ),
        migrations.AddField(
            model_name='player',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='originium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='orundum',
            field=models.IntegerField(default=0),
        ),
    ]
